# docker system prune -a
# docker rm -vf $(docker ps -a -q)
# docker rmi -f $(docker images -a -q)

version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  envoy:
    image: envoyproxy/envoy:latest
    restart: always
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "host"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres-data:



#  mongo:
#    image: mongo
#    restart: always
##    env_file: .env
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: default
#      MONGO_INITDB_ROOT_PASSWORD: password
#    ports:
#      - 27017:27017
#    volumes:
#      - type: bind
#        source: ./mongo/data
#        target: /data/db

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: default
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password